account_id = "8f0c2f2271ff857947d9a5b2c38595a0"
zone_id = "cb31764917040dd0b9a7b79e1ec099df"

main = "build/prod.js"
name = ""
workers_dev = false
route = "https://"
compatibility_date = "2022-09-09"
usage_model = "bundled"

[dev]
port = 8787
local_protocol = "http"
